spring.application.name=ticket-inventory-service

server.port = 8082

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3316/ticket_inventory_service_db
spring.datasource.username = root
spring.datasource.password = mysql
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path = /swagger-ui.html

# For Documentation In Form Of JSON
springdoc.api-docs.path = /api-docs
