spring.application.name=fifaWorldCup_NotificationService

server.port = 8083

# Mail Properties
#spring.mail.host = sandbox.smtp.mailtrap.io
#spring.mail.port = 2525
#spring.mail.username = e6e2bfe789017e
#spring.mail.password = a5a5c9db0d1af9


#bdoc xwpe jpsn xnqh

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=fifaWorldCupTicketSupport@gmail.com
#spring.mail.password=<password>
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notificationService2

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
#spring.kafka.consumer.properties.schema.registry.url = http://127.0.0.1:8085

spring.kafka.consumer.properties.spring.json.trusted.packages=com.fifa.fifaWorldCup_NotificationService.event

spring.kafka.consumer.properties.spring.json.type.mapping=com.fifa.fifaWorldCup_OrderService.event.OrderPlacedEvent:com.fifa.fifaWorldCup_NotificationService.event.OrderPlacedEvent

#spring.kafka.consumer.properties.spring.json.value.default.type=com.RollNo8.microservices.order.event.OrderPlacedEvent


# Command To Start it : docker run -d -p 1025:1025 -p 8025:8025 axllent/mailpit
spring.mail.host=localhost
spring.mail.port=1025




