spring.application.name=fifaWorldCup_api_gateway

server.port = 9000
server.servlet.context-path = /buytickets

logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.web.servlet.function=TRACE
